apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 3.5.0
    helm:
      releaseName: aws-load-balancer-controller
      values: |
        clusterName: dev-eks
        region: us-west-1
        replicaCount: 2
        image:
          tag: v3.5.0
        controllerConfig:
          featureGates:
            ALBGatewayAPI: true
        serviceAccount:
          create: false
          name: aws-load-balancer-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true